using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text;

namespace DotPointers.OneOf.Generator
{
	public static class OneOfSourceGenerator
	{
		private const string Inline = "[MethodImpl(MethodImplOptions.AggressiveInlining)]";
		private const string VoidType = "global::DotPointers.OneOf.Void";
		private const string CompilerGeneratedAttribute = "[CompilerGenerated]";

		public static string GenerateSource(GenerationModel model)
		{
			bool isClass = model.TypeKind.Contains("class");
			string read = isClass ? string.Empty : " readonly";
			var (layout, reason) = DetermineLayout(model);

			int count = model.TypeArgs.Length;
			string enumName = $"OneOf{model.Name}";
			string unionName = $"__DataUnion_{model.Name}";
			var sb = new StringBuilder(4096);

			bool hasRef = model.TypeArgs.Any(static t => t.IsReferenceType);
			bool hasVal = model.TypeArgs.Any(static t => !t.IsReferenceType);

			var uniqTypes = model.TypeArgs.Where(x => model.TypeArgs.Count(y => y.FullName == x.FullName) <= 1).Select(x => model.TypeArgs.IndexOf(x)).ToArray();
			var sameTypes = model.TypeArgs.Where(x => model.TypeArgs.Count(y => y.FullName == x.FullName) >= 2).Select(x => model.TypeArgs.IndexOf(x)).ToArray();

			#region Using
			sb.AppendLine($"// <auto-generated by {nameof(OneOfGenerator)} />");
			sb.AppendLine($"// Layout: {layout}{(string.IsNullOrEmpty(reason) ? string.Empty : " because " + reason)}");
			sb.AppendLine("#nullable enable");
			sb.AppendLine("using System;");
			sb.AppendLine("using System.Linq;");
			sb.AppendLine("using System.Collections;");
			sb.AppendLine("using System.Collections.Generic;");
			sb.AppendLine("using System.Runtime.InteropServices;");
			sb.AppendLine("using System.Runtime.CompilerServices;");
			sb.AppendLine("using System.Diagnostics;");
			sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
			sb.AppendLine("using System.Threading.Tasks;");
			sb.AppendLine("using DotPointers;");
			sb.AppendLine();
			#endregion

			sb.AppendLine($"namespace {model.Namespace}");
			sb.AppendLine("{");

			#region SubStruct
			if (layout == OneOfLayoutKind.ExplicitUnion && hasVal)
			{
				sb.AppendLine("\t[StructLayout(LayoutKind.Explicit)]");
				sb.AppendLine($"\tinternal struct {unionName}");
				sb.AppendLine("\t{");
				for (int i = 0; i < count; i++)
				{
					if (!model.TypeArgs[i].IsReferenceType && model.TypeArgs[i].FullName != VoidType)
					{
						sb.AppendLine($"\t\t[FieldOffset(0)] public {model.TypeArgs[i].FullName} _v{i};");
					}
				}
				sb.AppendLine("\t}");
				sb.AppendLine();
			}
			#endregion

			#region Definition

			sb.AppendLine($"\t[DebuggerDisplay(\"{{DebuggerDisplay,nq}}\")]");
			sb.AppendLine($"\t{CompilerGeneratedAttribute}");
			sb.Append($"\t{model.TypeKind.Replace("struct", "partial struct").Replace("class", "partial class")} {model.FullName}");
			if (!model.IsRef)
			{
				sb.Append($" : IEquatable<{model.FullName}>");
			}
			sb.AppendLine();
			sb.AppendLine("\t{");

			sb.AppendLine($"\t\tprivate readonly {enumName} _kind;");

			if (layout == OneOfLayoutKind.Boxing)
			{
				sb.AppendLine($"\t\tprivate readonly object? _value;");
			}
			else if (layout == OneOfLayoutKind.Composition)
			{
				for (int i = 0; i < count; i++)
				{
					if (model.TypeArgs[i].FullName != VoidType)
					{
						sb.AppendLine($"\t\tprivate readonly {model.TypeArgs[i].FullName} _v{i};");
					}
				}
			}
			else
			{
				if (hasRef)
				{
					sb.AppendLine($"\t\tprivate readonly object? _ref;");
				}
				if (hasVal)
				{
					sb.AppendLine("\t#pragma warning disable CS0649");
					sb.AppendLine($"\t\tprivate readonly {unionName} _data;");
					sb.AppendLine("\t#pragma warning restore CS0649");
				}
			}
			sb.AppendLine();

			#endregion

			#region Constructors
			if (isClass)
			{
				sb.AppendLine("\t\t#pragma warning disable CS8618");
			}
			if (!model.AllowEmpty)
			{
				if (!isClass)
				{
					sb.AppendLine($"\t\tpublic {model.Name}() {{ Unsafe.SkipInit(out this); throw new ArgumentException(); }}");
				}
				else
				{
					sb.AppendLine($"\t\tpublic {model.Name}() {{ throw new ArgumentException(); }}");
				}
				sb.AppendLine();
			}

			var typeGroups = model.TypeArgs
				.Select((type, index) => (type, index))
				.GroupBy(x => x.type.FullName);

			foreach (var group in typeGroups)
			{
				var type = group.First().type;
				var indices = group.Select(x => x.index).ToList();

				if (indices.Count == 1)
				{
					int i = indices[0];
					var field = model.FieldNames[i];
					sb.AppendLine($"\t\tpublic {model.Name}({type.FullName} value)");
					sb.AppendLine("\t\t{");
					if (!isClass)
					{
						sb.AppendLine("\t\t\tUnsafe.SkipInit(out this);");
					}
					GenerateConstructorBody(sb, type, i, layout);
					sb.AppendLine($"\t\t\tthis._kind = {enumName}.{field};");
					sb.AppendLine("\t\t}");
				}
				else
				{
					sb.AppendLine($"\t\tpublic {model.Name}({type.FullName} value, {enumName} kind)");
					sb.AppendLine("\t\t{");
					if (!isClass)
					{
						sb.AppendLine("\t\t\tUnsafe.SkipInit(out this);");
					}

					sb.Append("\t\t\tif (");
					sb.Append(string.Join(" && ", indices.Select(i => $"kind != {enumName}.{model.FieldNames[i]}")));
					sb.AppendLine(")");
					sb.AppendLine($"\t\t\t{{");
					sb.AppendLine($"\t\t\t\tthrow new ArgumentException($\"Kind {{kind}} is not valid for type {type.ShortName}\");");
					sb.AppendLine($"\t\t\t}}");
					sb.AppendLine();

					for (int i = 0; i < indices.Count; i++)
					{
						sb.AppendLine($"\t\t\t{(i > 0 ? "else " : string.Empty)}if (kind == {enumName}.{model.FieldNames[indices[i]]})");
						sb.AppendLine("\t\t\t{");

						sb.Append("\t");
						GenerateConstructorBody(sb, type, indices[i], layout);

						sb.AppendLine("\t\t\t}");
					}

					sb.AppendLine("\t\t\tthis._kind = kind;");
					sb.AppendLine("\t\t}");
				}
				sb.AppendLine();
			}

			void GenerateConstructorBody(StringBuilder builder, GenerationModel.TypeInfoModel t, int index, OneOfLayoutKind l)
			{
				if (t.IsReferenceType)
				{
					builder.AppendLine("\t\t\tif (value == null) { throw new ArgumentNullException(nameof(value)); }");
					if (l == OneOfLayoutKind.Boxing) { builder.AppendLine("\t\t\tthis._value = value;"); }
					else if (l == OneOfLayoutKind.Composition) { builder.AppendLine($"\t\t\tthis._v{index} = value;"); }
					else { builder.AppendLine("\t\t\tthis._ref = value;"); }
				}
				else
				{
					if (t.FullName != VoidType)
					{
						if (l == OneOfLayoutKind.Boxing) { builder.AppendLine("\t\t\tthis._value = value;"); }
						else if (l == OneOfLayoutKind.Composition) { builder.AppendLine($"\t\t\tthis._v{index} = value;"); }
						else { builder.AppendLine($"\t\t\tUnsafe.As<{unionName}, {t.FullName}>(ref Unsafe.AsRef(in _data)) = value;"); }
					}
				}
			}

			if (isClass)
			{
				sb.AppendLine("\t\t#pragma warning restore CS8618");
			}

			#endregion

			#region Tuple Conversion 

			if (!model.IsRef && model.TypeArgs.Length <= 7)
			{
				var tupleTypes = string.Join(", ", model.TypeArgs.Select(t => $"{t.FullName}?"));
				var tupleFull = $"(int Kind, {tupleTypes})";

				sb.AppendLine($"\t\tpublic{read} {tupleFull} AsTuple => _kind switch");
				sb.AppendLine("\t\t{");
				for (int i = 0; i < count; i++)
				{
					var values = Enumerable.Repeat("default", count).ToArray();
					values[i] = $"{model.FieldNames[i]}Force";
					sb.AppendLine($"\t\t\t{enumName}.{model.FieldNames[i]} => ({i + 1}, {string.Join(", ", values)}),");
				}
				sb.AppendLine("\t\t\t_ => (0, " + string.Join(", ", Enumerable.Repeat("default", count)) + ")");
				sb.AppendLine("\t\t};");
				sb.AppendLine();

				sb.AppendLine($"\t\t{Inline}");
				sb.AppendLine($"\t\tpublic static {model.FullName} FromTuple({tupleFull} tuple) => tuple.Kind switch");
				sb.AppendLine("\t\t{");
				for (int i = 0; i < count; i++)
				{
					if (sameTypes.Contains(i))
					{
						sb.AppendLine($"\t\t\t{i + 1} => new(({model.TypeArgs[i].FullName})tuple.Item{i + 2}!, {enumName}.{model.FieldNames[i]}),");
					}
					else
					{
						sb.AppendLine($"\t\t\t{i + 1} => new(({model.TypeArgs[i].FullName})tuple.Item{i + 2}!),");
					}
				}
				sb.AppendLine($"\t\t\t_ => {(model.AllowEmpty ? "Empty" : "throw new InvalidOperationException(\"Empty OneOf not allowed\")")}");
				sb.AppendLine("\t\t};");
				sb.AppendLine();

				sb.AppendLine($"\t\t{Inline}");
				sb.AppendLine($"\t\tpublic static implicit operator {model.FullName}({tupleFull} tuple) => FromTuple(tuple);");
				sb.AppendLine();
			}

			#endregion

			if (model.AllowEmpty)
			{
				sb.AppendLine($"\t\tpublic static {model.FullName} Empty => new();");
				sb.AppendLine();
			}

			#region GetForce

			for (int i = 0; i < count; i++)
			{
				var type = model.TypeArgs[i];
				var field = model.FieldNames[i];
				sb.Append($"\t\tprivate{read} {type.FullName} {field}Force => ");

				if (layout == OneOfLayoutKind.Boxing)
				{
					if (model.TypeArgs[i].FullName != VoidType)
					{
						sb.Append($"({type.FullName})_value!;");
					}
					else
					{
						sb.Append("default;");
					}
				}
				else if (layout == OneOfLayoutKind.Composition)
				{
					if (model.TypeArgs[i].FullName != VoidType)
					{
						sb.Append($"_v{i};");
					}
					else
					{
						sb.Append("default;");
					}
				}
				else if (type.IsReferenceType)
				{
					sb.Append($"({type.FullName})_ref!;");
				}
				else
				{
					sb.Append($"Unsafe.As<{unionName}, {type.FullName}>(ref Unsafe.AsRef(in _data));");
				}
				sb.AppendLine();
			}
			sb.AppendLine();

			#endregion

			#region Get / Is

			sb.AppendLine($"\t\tpublic{read} {enumName} Kind => _kind;");
			sb.AppendLine($"\t\tpublic{read} object? BoxValue => _kind switch");
			sb.AppendLine($"\t\t{{");
			for (int i = 0; i < count; i++)
			{
				sb.AppendLine($"\t\t\t{enumName}.{model.FieldNames[i]} => (object?){model.FieldNames[i]}Force,");
			}
			sb.AppendLine($"\t\t\t_ => null,");
			sb.AppendLine($"\t\t}};");

			for (int i = 0; i < count; i++)
			{
				var type = model.TypeArgs[i];
				var field = model.FieldNames[i];
				sb.AppendLine($"\t\tpublic{read} {type.FullName} {field}           => _kind == {enumName}.{field} ? {field}Force : throw new InvalidOperationException($\"Cannot access {field}. Current kind is {{_kind}}\");");
				sb.AppendLine($"\t\tpublic{read} {type.FullName}? {field}OrDefault => _kind == {enumName}.{field} ? {field}Force : default;");
			}
			sb.AppendLine();

			if (model.AllowEmpty)
			{
				sb.AppendLine($"\t\tpublic{read} bool IsEmpty => _kind == {enumName}.Empty;");
			}
			foreach (var field in model.FieldNames)
			{
				sb.AppendLine($"\t\tpublic{read} bool Is{field} => _kind == {enumName}.{field};");
			}
			sb.AppendLine();

			#endregion

			#region TryGet / Is

			for (int i = 0; i < count; i++)
			{
				var type = model.TypeArgs[i];
				var field = model.FieldNames[i];
				sb.AppendLine($"\t\t{Inline}");
				sb.AppendLine($"\t\tpublic{read} bool TryGet{field}([NotNullWhen(true)] out {type.FullName}{(type.IsReferenceType ? "?" : string.Empty)} OutValue)");
				sb.AppendLine("\t\t{");
				sb.AppendLine($"\t\t\tif (_kind == {enumName}.{field})");
				sb.AppendLine("\t\t\t{");
				sb.AppendLine($"\t\t\t\tOutValue = {field}Force!;");
				sb.AppendLine("\t\t\t\treturn true;");
				sb.AppendLine("\t\t\t}");
				sb.AppendLine("\t\t\tOutValue = default!;");
				sb.AppendLine("\t\t\treturn false;");
				sb.AppendLine("\t\t}");
				sb.AppendLine();
			}

			sb.AppendLine($"\t\t{Inline}");
			sb.AppendLine($"\t\tpublic{read} bool TryGet<TGet>([NotNullWhen(true)] out TGet? value)");
			sb.AppendLine("\t\t{");

			var grouped = model.TypeArgs.GroupBy(t => t.FullName);
			foreach (var group in grouped)
			{
				sb.AppendLine($"\t\t\tif (typeof(TGet) == typeof({group.Key}))");
				sb.AppendLine("\t\t\t{");
				foreach (var t in group)
				{
					int index = model.TypeArgs.IndexOf(t);
					sb.AppendLine($"\t\t\t\tif (_kind == {enumName}.{model.FieldNames[index]})");
					sb.AppendLine("\t\t\t\t{");
					sb.AppendLine($"\t\t\t\t\tvar temp = {model.FieldNames[index]}Force;");
					sb.AppendLine($"\t\t\t\t\tvalue = Unsafe.As<{group.Key}, TGet>(ref temp)!;");
					sb.AppendLine("\t\t\t\t\treturn true;");
					sb.AppendLine("\t\t\t\t}");
				}
				sb.AppendLine("\t\t\t}");
			}

			sb.AppendLine("\t\t\tvalue = default;");
			sb.AppendLine("\t\t\treturn false;");
			sb.AppendLine("\t\t}");
			sb.AppendLine();

			#endregion

			#region TryPick

			for (int i = 0; i < count; i++)
			{
				var type = model.TypeArgs[i];
				var field = model.FieldNames[i];
				sb.AppendLine($"\t\t{Inline}");
				sb.AppendLine($"\t\tpublic{read} bool TryPick{field}([NotNullWhen(true)] out {type.FullName}{(type.IsReferenceType ? "?" : string.Empty)} OutValue, [NotNullWhen(false)] out {model.FullName}{(model.TypeKind.Contains("class") ? "?" : string.Empty)} Remainder)");
				sb.AppendLine("\t\t{");
				sb.AppendLine($"\t\t\tif (_kind == {enumName}.{field})");
				sb.AppendLine("\t\t\t{");
				sb.AppendLine($"\t\t\t\tOutValue = {field}Force!;");
				sb.AppendLine($"\t\t\t\tRemainder = default!;");
				sb.AppendLine("\t\t\t\treturn true;");
				sb.AppendLine("\t\t\t}");
				sb.AppendLine("\t\t\tRemainder = this;");
				sb.AppendLine("\t\t\tOutValue = default!;");
				sb.AppendLine("\t\t\treturn false;");
				sb.AppendLine("\t\t}");
				sb.AppendLine();
			}

			#endregion

			#region Switch / Match

			sb.AppendLine($"\t\t{Inline}");
			sb.Append($"\t\tpublic{read} void Switch(");
			for (int i = 0; i < count; i++)
			{
				var type = model.TypeArgs[i];
				var field = model.FieldNames[i];
				sb.Append($"Action<{type.FullName}> On{field}");
				if (i < count - 1)
				{
					sb.Append(", ");
				}
			}
			if (model.AllowEmpty)
			{
				sb.Append(", Action OnEmpty");
			}
			sb.AppendLine(")");
			sb.AppendLine("\t\t{");
			sb.AppendLine("\t\t\tswitch(_kind)");
			sb.AppendLine("\t\t\t{");
			for (int i = 0; i < count; i++)
			{
				var field = model.FieldNames[i];
				sb.AppendLine($"\t\t\t\tcase {enumName}.{model.FieldNames[i]}: {{ On{field}.Invoke({model.FieldNames[i]}); break; }}");
			}
			if (model.AllowEmpty)
			{
				sb.AppendLine("\t\t\t\tdefault: { OnEmpty.Invoke(); break; }");
			}
			else
			{
				sb.AppendLine($"\t\t\t\tdefault: {{ throw new ArgumentNullException(\"{model.Name} is empty\"); }}");
			}
			sb.AppendLine("\t\t\t};");
			sb.AppendLine("\t\t}");
			sb.AppendLine();


			sb.AppendLine($"\t\t{Inline}");
			sb.Append($"\t\tpublic{read} TResult Match<TResult>(");
			for (int i = 0; i < count; i++)
			{
				var type = model.TypeArgs[i];
				var field = model.FieldNames[i];
				sb.Append($"Func<{type.FullName}, TResult> On{field}");
				if (i < count - 1)
				{
					sb.Append(", ");
				}
			}
			if (model.AllowEmpty)
			{
				sb.Append(", Func<TResult> OnEmpty");
			}
			sb.AppendLine(")");
			sb.AppendLine("\t\t{");
			sb.AppendLine("\t\t\tswitch(_kind)");
			sb.AppendLine("\t\t\t{");
			for (int i = 0; i < count; i++)
			{
				var field = model.FieldNames[i];
				sb.AppendLine($"\t\t\t\tcase {enumName}.{model.FieldNames[i]}: {{ return On{field}.Invoke({model.FieldNames[i]}); }}");
			}
			if (model.AllowEmpty)
			{
				sb.AppendLine("\t\t\t\tdefault: { return OnEmpty.Invoke(); }");
			}
			else
			{
				sb.AppendLine($"\t\t\t\tdefault: {{ throw new ArgumentNullException(\"{model.Name} is empty\"); }}");
			}
			sb.AppendLine("\t\t\t};");
			sb.AppendLine("\t\t}");
			sb.AppendLine();

			#endregion

			#region Async SwitchAsync / MatchAsync
			if (!model.IsRef)
			{
				sb.AppendLine($"\t\t{Inline}");
				sb.Append($"\t\tpublic{read} async ValueTask SwitchAsync(");
				for (int i = 0; i < count; i++)
				{
					var type = model.TypeArgs[i];
					var field = model.FieldNames[i];
					sb.Append($"Func<{type.FullName}, ValueTask> On{field}");
					if (i < count - 1 || model.AllowEmpty)
					{
						sb.Append(", ");
					}
				}
				if (model.AllowEmpty)
				{
					sb.Append("Func<ValueTask> OnEmpty");
				}
				sb.AppendLine(")");
				sb.AppendLine("\t\t{");
				sb.AppendLine("\t\t\tswitch(_kind)");
				sb.AppendLine("\t\t\t{");
				for (int i = 0; i < count; i++)
				{
					sb.AppendLine($"\t\t\t\tcase {enumName}.{model.FieldNames[i]}: {{ await On{model.FieldNames[i]}.Invoke({model.FieldNames[i]}Force); break; }}");
				}
				if (model.AllowEmpty)
				{
					sb.AppendLine("\t\t\t\tdefault: { await OnEmpty.Invoke(); break; }");
				}
				else
				{
					sb.AppendLine($"\t\t\t\tdefault: {{ throw new InvalidOperationException(\"{model.Name} is empty\"); }}");
				}
				sb.AppendLine("\t\t\t};");
				sb.AppendLine("\t\t}");
				sb.AppendLine();

				sb.AppendLine($"\t\t{Inline}");
				sb.Append($"\t\tpublic{read} async ValueTask<TResult> MatchAsync<TResult>(");
				for (int i = 0; i < count; i++)
				{
					var type = model.TypeArgs[i];
					var field = model.FieldNames[i];
					sb.Append($"Func<{type.FullName}, ValueTask<TResult>> On{field}");
					if (i < count - 1 || model.AllowEmpty)
					{
						sb.Append(", ");
					}
				}
				if (model.AllowEmpty)
				{
					sb.Append("Func<ValueTask<TResult>> OnEmpty");
				}
				sb.AppendLine(")");
				sb.AppendLine("\t\t{");
				sb.AppendLine("\t\t\treturn _kind switch");
				sb.AppendLine("\t\t\t{");
				for (int i = 0; i < count; i++)
				{
					sb.AppendLine($"\t\t\t\t{enumName}.{model.FieldNames[i]} => await On{model.FieldNames[i]}.Invoke({model.FieldNames[i]}Force),");
				}
				if (model.AllowEmpty)
				{
					sb.AppendLine("\t\t\t\t_ => await OnEmpty.Invoke()");
				}
				else
				{
					sb.AppendLine($"\t\t\t\t_ => throw new InvalidOperationException(\"{model.Name} is empty\")");
				}
				sb.AppendLine("\t\t\t};");
				sb.AppendLine("\t\t}");
			}
			#endregion

			#region Map

			for (int i = 0; i < count; i++)
			{
				var type = model.TypeArgs[i];
				var field = model.FieldNames[i];

				sb.AppendLine($"\t\t{Inline}");
				sb.AppendLine($"\t\tpublic{read} {model.FullName} Map{field}(Func<{type.FullName}, {type.FullName}> mapper)");
				sb.AppendLine("\t\t{");
				sb.AppendLine($"\t\t\tif (_kind == {enumName}.{field})");
				sb.AppendLine("\t\t\t{");
				if (sameTypes.Contains(i))
				{
					sb.AppendLine($"\t\t\t\treturn new {model.FullName}(mapper.Invoke({field}Force), {enumName}.{field});");
				}
				else
				{
					sb.AppendLine($"\t\t\t\treturn new {model.FullName}(mapper.Invoke({field}Force));");
				}
				sb.AppendLine("\t\t\t}");
				sb.AppendLine("\t\t\treturn this;");
				sb.AppendLine("\t\t}");
				sb.AppendLine();
			}

			#endregion

			#region Equality

			if (!model.IsRef)
			{
				if (!model.UserFuncs.Any(f =>
					f.Item1 == "Equals" &&
					f.Item2.Length == 1 &&
					f.Item2[0] == model.FullName))
				{
					sb.AppendLine($"\t\tpublic{read} bool Equals({model.FullName}{(isClass ? "?" : string.Empty)} other)");
					sb.AppendLine("\t\t{");
					if (isClass)
					{
						sb.AppendLine("\t\t\tif (other == null) { return false; }");
					}
					sb.AppendLine("\t\t\tif (_kind != other._kind) { return false; }");
					sb.AppendLine("\t\t\treturn _kind switch");
					sb.AppendLine("\t\t\t{");
					for (int i = 0; i < count; i++)
					{
						sb.AppendLine($"\t\t\t\t{enumName}.{model.FieldNames[i]} => EqualityComparer<{model.TypeArgs[i].FullName}>.Default.Equals({model.FieldNames[i]}Force, other.{model.FieldNames[i]}Force),");
					}
					sb.AppendLine("\t\t\t\t_ => true");
					sb.AppendLine("\t\t\t};");
					sb.AppendLine("\t\t}");
					sb.AppendLine();
				}

				if (!model.UserFuncs.Any(f =>
					f.Item1 == "Equals" &&
					f.Item2.Length == 1 &&
					(f.Item2[0] == "object?" || f.Item2[0] == "object")))
				{
					sb.AppendLine($"\t\tpublic{read} override bool Equals(object? obj) => obj is " + model.FullName + " other && Equals(other);");
					sb.AppendLine();
				}

				if (!model.UserFuncs.Any(f =>
					f.Item1 == "GetHashCode()" &&
					f.Item2.Length == 0))
				{
					sb.AppendLine($"\t\tpublic{read} override int GetHashCode()");
					sb.AppendLine("\t\t{");
					sb.AppendLine("\t\t\tvar hash = new HashCode();");
					sb.AppendLine("\t\t\thash.Add(_kind);");
					sb.AppendLine("\t\t\tswitch(_kind)");
					sb.AppendLine("\t\t\t{");
					for (int i = 0; i < count; i++)
					{
						sb.AppendLine($"\t\t\t\tcase {enumName}.{model.FieldNames[i]}: {{ hash.Add({model.FieldNames[i]}Force); break; }}");
					}
					sb.AppendLine("\t\t\t}");
					sb.AppendLine("\t\t\treturn hash.ToHashCode();");
					sb.AppendLine("\t\t}");
					sb.AppendLine();
				}

				if (!isClass)
				{
					sb.AppendLine($"\t\tpublic static bool operator ==({model.FullName} left, {model.FullName} right) => left.Equals(right);");
					sb.AppendLine($"\t\tpublic static bool operator !=({model.FullName} left, {model.FullName} right) => !left.Equals(right);");
				}
				else
				{
					sb.AppendLine($"\t\tpublic static bool operator ==({model.FullName}? left, {model.FullName}? right) => ReferenceEquals(left, right) ? true : (((object?)left) == null ? false : left.Equals(right));");
					sb.AppendLine($"\t\tpublic static bool operator !=({model.FullName}? left, {model.FullName}? right) => ReferenceEquals(left, right) ? false :(((object?)left) == null ? true : !left.Equals(right));");
				}
				sb.AppendLine();
			}

			#endregion

			#region Deconstruct

			sb.Append($"\t\tpublic{read} void Deconstruct(out {enumName} kind");
			for (int i = 0; i < count; i++)
			{
				sb.Append($", out {model.TypeArgs[i].FullName}? {model.FieldNames[i].ToLower()}");
			}
			sb.AppendLine(")");
			sb.AppendLine("\t\t{");
			sb.AppendLine("\t\t\tkind = _kind;");
			for (int i = 0; i < count; i++)
			{
				sb.AppendLine($"\t\t\t{model.FieldNames[i].ToLower()} = Is{model.FieldNames[i]} ? {model.FieldNames[i]}Force : default;");
			}
			sb.AppendLine("\t\t}");
			sb.AppendLine();

			#endregion

			#region Operators

			foreach (int i in uniqTypes)
			{
				var type = model.TypeArgs[i];
				var field = model.FieldNames[i];
				if (model.TypeArgs.Count(x => x.FullName == type.FullName) >= 2) { continue; }
				sb.AppendLine($"\t\t{Inline}");
				sb.Append($"\t\tpublic static implicit operator {model.FullName}({type.FullName} value) => ");
				if (type.IsReferenceType)
				{
					sb.AppendLine("(value == null) ? throw new ArgumentNullException(nameof(value)) : new(value);");
				}
				else
				{
					sb.AppendLine("new(value);");
				}
				sb.AppendLine($"\t\t{Inline}");
				sb.AppendLine($"\t\tpublic static explicit operator {type.FullName}({model.FullName} source) => source.{field};");
				sb.AppendLine();
			}

			#endregion

			#region IEnumerable

			if (!model.IsRef)
			{
				sb.AppendLine($"\t\t{Inline}");
				sb.AppendLine($"\t\tpublic{read} IEnumerable<{model.FullName}> AsEnumerable()");
				sb.AppendLine("\t\t{");
				if (model.AllowEmpty)
				{
					sb.AppendLine("\t\t\tif (IsEmpty) { yield break; }");
				}
				sb.AppendLine("\t\t\tyield return this;");
				sb.AppendLine("\t\t}");
				sb.AppendLine();
			}

			#endregion

			#region ToString / DebuggerDisplay

			if (!model.UserFuncs.Any(f =>
					f.Item1 == "ToString" &&
					f.Item2.Length == 0 ))
			{
				sb.AppendLine($"\t\t{Inline}");
				sb.AppendLine($"\t\tpublic{read} override string? ToString() => _kind switch");
				sb.AppendLine("\t\t{");
				for (int i = 0; i < count; i++)
				{
					sb.AppendLine($"\t\t\t{enumName}.{model.FieldNames[i]} => {model.FieldNames[i]}Force!.ToString(),");
				}
				sb.AppendLine("\t\t\t_ => \"Empty\"");
				sb.AppendLine("\t\t};");
				sb.AppendLine();
			}

			sb.AppendLine("\t\t#if DEBUG");
			sb.AppendLine($"\t\tprivate{read} string DebuggerDisplay => _kind switch");
			sb.AppendLine("\t\t{");
			for (int i = 0; i < count; i++)
			{
				sb.AppendLine($"\t\t\t{enumName}.{model.FieldNames[i]} => $\"{model.TypeArgs[i].ShortName}({{{model.FieldNames[i]}}})\",");
			}
			sb.AppendLine("\t\t\t_ => \"Empty\"");
			sb.AppendLine("\t\t};");
			sb.AppendLine("\t\t#endif");

			#endregion

			sb.AppendLine($"\t\tpublic enum {enumName} : int");
			sb.AppendLine("\t\t{");
			sb.AppendLine("\t\t\tEmpty = 0,");
			for (int i = 0; i < count; i++)
			{
				sb.AppendLine($"\t\t\t{model.FieldNames[i]} = {i + 1},");
			}
			sb.AppendLine("\t\t}");
			sb.AppendLine("\t}");

			sb.Append("}");
			return sb.ToString();
		}

		public static string GenerateSystemJsonSource(GenerationModel model)
		{
			var jsonClass = $"{model.Name}JsonConverter";
			string enumName = $"OneOf{model.Name}";
			var fullName = model.FullName;
			string read = model.TypeKind.Contains("class") ? string.Empty : " readonly";

			StringBuilder sb = new(2048);
			sb.AppendLine($"// <auto-generated by {nameof(OneOfGenerator)} />");
			sb.AppendLine("#nullable enable");
			sb.AppendLine("using System;");
			sb.AppendLine("using System.Text.Json;");
			sb.AppendLine("using System.Text.Json.Serialization;");

			sb.AppendLine("#if NET7_0_OR_GREATER");
			sb.AppendLine("using System.Text;");
			sb.AppendLine("#endif");

			sb.AppendLine();
			sb.AppendLine($"namespace {model.Namespace}");
			sb.AppendLine("{");
			sb.AppendLine($"\t[JsonConverter(typeof({jsonClass}))]");
			sb.AppendLine($"\tpartial {model.TypeKind} {fullName}");
			sb.AppendLine("\t{");
			sb.AppendLine($"\t\tinternal class {jsonClass} : JsonConverter<{fullName}>");
			sb.AppendLine("\t\t{");
			sb.AppendLine($"\t\t\tprivate static{read} JsonEncodedText KindProp = JsonEncodedText.Encode(\"Kind\");");
			sb.AppendLine($"\t\t\tprivate static{read} JsonEncodedText ValueProp = JsonEncodedText.Encode(\"Value\");");
			sb.AppendLine();

			sb.AppendLine($"\t\t\tpublic override {fullName} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)");
			sb.AppendLine("\t\t\t{");
			sb.AppendLine("\t\t\t\tif (reader.TokenType != JsonTokenType.StartObject)");
			sb.AppendLine("\t\t\t\t{");
			sb.AppendLine("\t\t\t\t\tthrow new JsonException(\"Expected StartObject token.\");");
			sb.AppendLine("\t\t\t\t}");
			sb.AppendLine();
			sb.AppendLine("\t\t\t\tint kindInt = 0;");
			sb.AppendLine("\t\t\t\tJsonElement valueElement = default;");
			sb.AppendLine("\t\t\t\tbool valueFound = false;");
			sb.AppendLine();
			sb.AppendLine("\t\t\t\twhile (reader.Read())");
			sb.AppendLine("\t\t\t\t{");
			sb.AppendLine("\t\t\t\t\tif (reader.TokenType == JsonTokenType.EndObject)");
			sb.AppendLine("\t\t\t\t\t{");
			sb.AppendLine("\t\t\t\t\t\tbreak;");
			sb.AppendLine("\t\t\t\t\t}");
			sb.AppendLine();
			sb.AppendLine("\t\t\t\t\tif (reader.TokenType != JsonTokenType.PropertyName)");
			sb.AppendLine("\t\t\t\t\t{");
			sb.AppendLine("\t\t\t\t\t\tcontinue;");
			sb.AppendLine("\t\t\t\t\t}");
			sb.AppendLine();

			sb.AppendLine("\t\t\t\t\t#if NET7_0_OR_GREATER");
			sb.AppendLine("\t\t\t\t\tif (reader.ValueTextEquals(\"Kind\"u8))");
			sb.AppendLine("\t\t\t\t\t#else");
			sb.AppendLine("\t\t\t\t\tif (reader.ValueTextEquals(KindProp.EncodedUtf8Bytes))");
			sb.AppendLine("\t\t\t\t\t#endif");
			sb.AppendLine("\t\t\t\t\t{");
			sb.AppendLine("\t\t\t\t\t\treader.Read();");
			sb.AppendLine("\t\t\t\t\t\tkindInt = reader.GetInt32();");
			sb.AppendLine("\t\t\t\t\t}");

			sb.AppendLine("\t\t\t\t\t#if NET7_0_OR_GREATER");
			sb.AppendLine("\t\t\t\t\telse if (reader.ValueTextEquals(\"Value\"u8))");
			sb.AppendLine("\t\t\t\t\t#else");
			sb.AppendLine("\t\t\t\t\tif (reader.ValueTextEquals(ValueProp.EncodedUtf8Bytes))");
			sb.AppendLine("\t\t\t\t\t#endif");
			sb.AppendLine("\t\t\t\t\t{");
			sb.AppendLine("\t\t\t\t\t\treader.Read();");
			sb.AppendLine("\t\t\t\t\t\tvalueElement = JsonElement.ParseValue(ref reader);");
			sb.AppendLine("\t\t\t\t\t\tvalueFound = true;");
			sb.AppendLine("\t\t\t\t\t}");
			sb.AppendLine("\t\t\t\t\telse");
			sb.AppendLine("\t\t\t\t\t{");
			sb.AppendLine("\t\t\t\t\t\treader.Skip();");
			sb.AppendLine("\t\t\t\t\t}");
			sb.AppendLine("\t\t\t\t}");
			sb.AppendLine();
			sb.AppendLine($"\t\t\t\tvar kind = ({enumName})kindInt;");
			sb.AppendLine("\t\t\t\treturn kind switch");
			sb.AppendLine("\t\t\t\t{");
			for (int i = 0; i < model.TypeArgs.Length; i++)
			{
				var type = model.TypeArgs[i].FullName;
				var field = model.FieldNames[i];
				sb.AppendLine($"\t\t\t\t\t{enumName}.{field} => valueFound ? new(valueElement.Deserialize<{type}?>(options) ?? default!{(model.TypeArgs.Count(x => x.FullName == type) >= 2 ? $", {enumName}.{field}" : string.Empty)}) : default!,");
			}
			if (model.AllowEmpty)
			{
				sb.AppendLine("\t\t\t\t\t_ => default");
			}
			else
			{
				sb.AppendLine("\t\t\t\t\t_ => throw new JsonException(\"Unknown Kind\")");
			}
			sb.AppendLine("\t\t\t\t};");
			sb.AppendLine("\t\t\t}");
			sb.AppendLine();
			sb.AppendLine($"\t\t\tpublic override void Write(Utf8JsonWriter writer, {fullName} value, JsonSerializerOptions options)");
			sb.AppendLine("\t\t\t{");
			sb.AppendLine("\t\t\t\twriter.WriteStartObject();");
			sb.AppendLine("\t\t\t\twriter.WriteNumber(KindProp, (int)value._kind);");
			if (model.AllowEmpty)
			{
				sb.AppendLine("\t\t\t\tif (value.IsEmpty)");
				sb.AppendLine("\t\t\t\t{");
				sb.AppendLine("\t\t\t\t\twriter.WriteEndObject();");
				sb.AppendLine("\t\t\t\t\treturn;");
				sb.AppendLine("\t\t\t\t}");
			}
			sb.AppendLine("\t\t\t\twriter.WritePropertyName(ValueProp);");
			sb.AppendLine("\t\t\t\tvalue.Switch(");
			for (int i = 0; i < model.TypeArgs.Length; i++)
			{
				sb.Append($"\t\t\t\t\ton{model.FieldNames[i]} => JsonSerializer.Serialize(writer, on{model.FieldNames[i]}, options)");
				if (i < model.TypeArgs.Length - 1 || model.AllowEmpty)
				{
					sb.AppendLine(",");
				}
				else
				{
					sb.AppendLine();
				}
			}
			if (model.AllowEmpty)
			{
				sb.AppendLine("\t\t\t\t\t() => { }");
			}

			sb.AppendLine("\t\t\t\t);");
			sb.AppendLine("\t\t\t\twriter.WriteEndObject();");
			sb.AppendLine("\t\t\t}");
			sb.AppendLine("\t\t}");
			sb.AppendLine("\t}");
			sb.Append("}");
			return sb.ToString();
		}

		public static string GenerateNewtonsoftJsonSource(GenerationModel model)
		{
			var jsonClass = $"{model.Name}NewtonsoftConverter";
			string enumName = $"OneOf{model.Name}";
			var fullName = model.FullName;
			bool isClass = model.TypeKind.Contains("class");

			StringBuilder sb = new(2048);
			sb.AppendLine($"// <auto-generated by {nameof(OneOfGenerator)} for Newtonsoft.Json support />");
			sb.AppendLine("#nullable enable");
			sb.AppendLine("using System;");
			sb.AppendLine("using Newtonsoft.Json;");
			sb.AppendLine("using Newtonsoft.Json.Linq;");
			sb.AppendLine();
			sb.AppendLine($"namespace {model.Namespace}");
			sb.AppendLine("{");
			sb.AppendLine($"\t[JsonConverter(typeof({jsonClass}))]");
			sb.AppendLine($"\tpartial {model.TypeKind} {fullName}");
			sb.AppendLine("\t{");
			sb.AppendLine($"\t\tinternal class {jsonClass} : JsonConverter<{fullName}>");
			sb.AppendLine("\t\t{");
			sb.AppendLine("\t\t\tprivate const string KindProp = \"Kind\";");
			sb.AppendLine("\t\t\tprivate const string ValueProp = \"Value\";");
			sb.AppendLine();

			sb.AppendLine($"\t\t\tpublic override {fullName}{(isClass ? "?" : string.Empty)} ReadJson(JsonReader reader, Type objectType, {fullName}{(isClass ? "?" : string.Empty)} existingValue, bool hasExistingValue, JsonSerializer serializer)");
			sb.AppendLine("\t\t\t{");
			sb.AppendLine("\t\t\t\tif (reader.TokenType == JsonToken.Null)");
			sb.AppendLine("\t\t\t\t{");
			sb.AppendLine("\t\t\t\t\treturn default;");
			sb.AppendLine("\t\t\t\t}");
			sb.AppendLine();
			sb.AppendLine("\t\t\t\tif (reader.TokenType != JsonToken.StartObject)");
			sb.AppendLine("\t\t\t\t{");
			sb.AppendLine("\t\t\t\t\tthrow new JsonException(\"Expected StartObject token.\");");
			sb.AppendLine("\t\t\t\t}");
			sb.AppendLine();
			sb.AppendLine("\t\t\t\tJObject jo = JObject.Load(reader);");
			sb.AppendLine();
			sb.AppendLine("\t\t\t\tif (!jo.TryGetValue(KindProp, StringComparison.OrdinalIgnoreCase, out JToken? kindToken))");
			sb.AppendLine("\t\t\t\t{");
			sb.AppendLine("\t\t\t\t\tthrow new JsonException(\"Missing 'Kind' property.\");");
			sb.AppendLine("\t\t\t\t}");
			sb.AppendLine();
			sb.AppendLine("\t\t\t\tint kindInt = kindToken.Value<int>();");
			sb.AppendLine($"\t\t\t\tvar kind = ({enumName})kindInt;");
			sb.AppendLine();
			sb.AppendLine("\t\t\t\tjo.TryGetValue(ValueProp, StringComparison.OrdinalIgnoreCase, out JToken? valueToken);");
			sb.AppendLine();
			sb.AppendLine("\t\t\t\treturn kind switch");
			sb.AppendLine("\t\t\t\t{");

			for (int i = 0; i < model.TypeArgs.Length; i++)
			{
				var type = model.TypeArgs[i].FullName;
				var field = model.FieldNames[i];
				sb.AppendLine($"\t\t\t\t\t{enumName}.{field} => valueToken != null ? new(valueToken.ToObject<{type}?>(serializer) ?? default!{(model.TypeArgs.Count(x => x.FullName == type) >= 2 ? $", {enumName}.{field}" : string.Empty)}) : default!,");
			}

			if (model.AllowEmpty)
			{
				sb.AppendLine("\t\t\t\t\t_ => default");
			}
			else
			{
				sb.AppendLine("\t\t\t\t\t_ => throw new JsonException($\"Unknown Kind: {kindInt}\")");
			}

			sb.AppendLine("\t\t\t\t};");
			sb.AppendLine("\t\t\t}");
			sb.AppendLine();

			sb.AppendLine($"\t\t\tpublic override void WriteJson(JsonWriter writer, {fullName}{(isClass ? "?" : string.Empty)} value, JsonSerializer serializer)");
			sb.AppendLine("\t\t\t{");
			sb.AppendLine("\t\t\t\twriter.WriteStartObject();");
			sb.AppendLine();
			if (isClass)
			{
				sb.AppendLine("\t\t\t\tif (value == null) { writer.WriteEndObject(); return; }");
			}
			sb.AppendLine();
			sb.AppendLine("\t\t\t\twriter.WritePropertyName(KindProp);");
			sb.AppendLine("\t\t\t\twriter.WriteValue((int)value._kind);");
			sb.AppendLine();

			if (model.AllowEmpty)
			{
				sb.AppendLine("\t\t\t\tif (value.IsEmpty)");
				sb.AppendLine("\t\t\t\t{");
				sb.AppendLine("\t\t\t\t\twriter.WriteEndObject();");
				sb.AppendLine("\t\t\t\t\treturn;");
				sb.AppendLine("\t\t\t\t}");
				sb.AppendLine();
			}

			sb.AppendLine("\t\t\t\twriter.WritePropertyName(ValueProp);");
			sb.AppendLine("\t\t\t\tvalue.Switch(");
			for (int i = 0; i < model.TypeArgs.Length; i++)
			{
				sb.Append($"\t\t\t\t\ton{model.FieldNames[i]} => serializer.Serialize(writer, on{model.FieldNames[i]})");
				if (i < model.TypeArgs.Length - 1 || model.AllowEmpty)
				{
					sb.AppendLine(",");
				}
				else
				{
					sb.AppendLine();
				}
			}

			if (model.AllowEmpty)
			{
				sb.AppendLine("\t\t\t\t\t() => { }");
			}

			sb.AppendLine("\t\t\t\t);");
			sb.AppendLine();
			sb.AppendLine("\t\t\t\twriter.WriteEndObject();");
			sb.AppendLine("\t\t\t}");
			sb.AppendLine("\t\t}");
			sb.AppendLine("\t}");
			sb.Append("}");

			return sb.ToString();
		}

		public static string GenerateMemoryPackSource(GenerationModel model)
		{
			var formatterClass = $"{model.Name}Formatter";
			string enumName = $"OneOf{model.Name}";
			var fullName = model.FullName;
			bool isClass = model.TypeKind.Contains("class");

			StringBuilder sb = new(2048);
			sb.AppendLine($"// <auto-generated by {nameof(OneOfGenerator)} for MemoryPack support />");
			sb.AppendLine("#nullable enable");
			sb.AppendLine("using System;");
			sb.AppendLine("using MemoryPack;");
			sb.AppendLine();
			sb.AppendLine($"namespace {model.Namespace}");
			sb.AppendLine("{");
			sb.AppendLine($"\tpartial {model.TypeKind} {fullName}");
			sb.AppendLine("\t{");

			sb.AppendLine($"\t\tstatic {model.Name}()");
			sb.AppendLine("\t\t{");
			sb.AppendLine($"\t\t\tMemoryPackFormatterProvider.Register(new {formatterClass}());");
			sb.AppendLine("\t\t}");
			sb.AppendLine();

			sb.AppendLine($"\t\tinternal class {formatterClass} : MemoryPackFormatter<{fullName}>");
			sb.AppendLine("\t\t{");

			sb.AppendLine($"\t\t\tpublic override void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer, scoped ref {fullName}{(isClass ? "?" : string.Empty)} value)");
			sb.AppendLine("\t\t\t{");
			if (isClass)
			{
				sb.AppendLine("\t\t\t\tif (value == null) { writer.WriteNullObjectHeader(); return; }");
			}
			sb.AppendLine("\t\t\t\twriter.WriteUnmanaged((byte)value._kind);");
			sb.AppendLine();
			sb.AppendLine("\t\t\t\tswitch (value._kind)");
			sb.AppendLine("\t\t\t\t{");

			for (int i = 0; i < model.TypeArgs.Length; i++)
			{
				var type = model.TypeArgs[i].FullName;
				var field = model.FieldNames[i];
				sb.AppendLine($"\t\t\t\t\tcase {enumName}.{field}:");
				sb.AppendLine($"\t\t\t\t\t\twriter.WriteValue<{type}>(value.{field}Force);");
				sb.AppendLine("\t\t\t\t\t\tbreak;");
			}

			sb.AppendLine("\t\t\t\t}");
			sb.AppendLine("\t\t\t}");
			sb.AppendLine();

			sb.AppendLine($"\t\t\tpublic override void Deserialize(ref MemoryPackReader reader, scoped ref {fullName}{(isClass ? "?" : string.Empty)} value)");
			sb.AppendLine("\t\t\t{");
			sb.AppendLine("\t\t\t\tif (reader.PeekIsNull())");
			sb.AppendLine("\t\t\t\t{");
			sb.AppendLine("\t\t\t\t\treader.Advance(1);");
			sb.AppendLine("\t\t\t\t\tvalue = default;");
			sb.AppendLine("\t\t\t\t\treturn;");
			sb.AppendLine("\t\t\t\t}");
			sb.AppendLine();

			sb.AppendLine("\t\t\t\treader.ReadUnmanaged(out byte k);");
			sb.AppendLine($"\t\t\t\tvar kind = ({enumName})k;");
			sb.AppendLine();

			sb.AppendLine("\t\t\t\tvalue = kind switch");
			sb.AppendLine("\t\t\t\t{");
			for (int i = 0; i < model.TypeArgs.Length; i++)
			{
				var type = model.TypeArgs[i].FullName;
				var field = model.FieldNames[i];
				sb.AppendLine($"\t\t\t\t\t{enumName}.{field} => new {fullName}(reader.ReadValue<{type}>()!{(model.TypeArgs.Count(x => x.FullName == type) >= 2 ? $", {enumName}.{field}" : string.Empty)}),");
			}

			sb.AppendLine("\t\t\t\t\t_ => default");
			sb.AppendLine("\t\t\t\t};");
			sb.AppendLine("\t\t\t}");
			sb.AppendLine("\t\t}");
			sb.AppendLine("\t}");
			sb.Append("}");

			return sb.ToString();
		}

		private static (OneOfLayoutKind Strategy, string Reason) DetermineLayout(GenerationModel model)
		{
			bool isClass = model.TypeKind.Contains("class");
			bool hasRefStructInside = model.TypeArgs.Any(t => t.IsRefStruct);

			if (model.RequestedLayout == OneOfLayoutKind.Boxing)
			{
				if (hasRefStructInside)
				{
					return (OneOfLayoutKind.Composition, "Boxing is impossible with ref structs");
				}
				return (OneOfLayoutKind.Boxing, string.Empty);
			}

			if (model.RequestedLayout == OneOfLayoutKind.ExplicitUnion)
			{
				if (isClass)
				{
					return (OneOfLayoutKind.Composition, "ExplicitUnion is not supported for classes");
				}
				if (model.IsGeneric)
				{
					return (OneOfLayoutKind.Composition, "ExplicitUnion is unstable with generic value types");
				}
				if (hasRefStructInside)
				{
					return (OneOfLayoutKind.Composition, "ExplicitUnion is not supported with ref structs");
				}
				return (OneOfLayoutKind.ExplicitUnion, string.Empty);
			}

			return (OneOfLayoutKind.Composition, "Default fallback");
		}
	}
}
