using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;

namespace DotPointers.OneOf.Generator
{
	public static class OneOfSourceGenerator
	{
		private const string Inline = "[MethodImpl(MethodImplOptions.AggressiveInlining)]";
		private const string VoidType = "global::DotPointers.OneOf.Void";
		private const string CompilerGeneratedAttribute = "[CompilerGenerated]";
		private const string ThrowHelper = "OneOfThrowHelper";

		public static string GenerateSource(GenerationModel model)
		{
			bool isClass = model.TypeKind.Contains("class");
			string read = isClass ? string.Empty : " readonly";
			var (layout, reason) = DetermineLayout(model);

			int count = model.TypeArgs.Length;
			string enumName = $"OneOf{model.Name}";
			string unionName = $"__DataUnion_{model.Name}";
			var sb = new IndentedWriter();

			bool hasRef = model.TypeArgs.Any(static t => t.IsReferenceType);
			bool hasVal = model.TypeArgs.Any(static t => !t.IsReferenceType);

			var uniqTypes = model.TypeArgs.Where(x => model.TypeArgs.Count(y => y.FullName == x.FullName) <= 1).Select(x => model.TypeArgs.IndexOf(x)).ToArray();
			var sameTypes = model.TypeArgs.Where(x => model.TypeArgs.Count(y => y.FullName == x.FullName) >= 2).Select(x => model.TypeArgs.IndexOf(x)).ToArray();

			bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);

			#region Using
			sb.AppendLine($"// <auto-generated by {nameof(OneOfGenerator)} />");
			sb.AppendLine($"// Layout: {layout}{(string.IsNullOrEmpty(reason) ? string.Empty : " because " + reason)}");
			sb.AppendLine("#nullable enable");
			sb.AppendLine("using System;");
			sb.AppendLine("using System.Linq;");
			sb.AppendLine("using System.Collections;");
			sb.AppendLine("using System.Collections.Generic;");
			sb.AppendLine("using System.Runtime.InteropServices;");
			sb.AppendLine("using System.Runtime.CompilerServices;");
			sb.AppendLine("using System.Diagnostics;");
			sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
			sb.AppendLine("using System.Threading.Tasks;");
			sb.AppendLine("using DotPointers;");
			sb.AppendLine();
			#endregion

			if (hasNamespace)
			{
				sb.AppendLine($"namespace {model.Namespace}");
				sb.AppendLine("{");
				sb.Increase();
			}


			#region SubStruct
			if (layout == OneOfLayoutKind.ExplicitUnion && hasVal)
			{
				sb.AppendLine("[StructLayout(LayoutKind.Explicit)]");
				sb.AppendLine($"internal struct {unionName}");
				using (sb.EnterScope())
				{
					for (int i = 0; i < count; i++)
					{
						if (!model.TypeArgs[i].IsReferenceType && model.TypeArgs[i].FullName != VoidType)
						{
							sb.AppendLine($"[FieldOffset(0)] public {model.TypeArgs[i].FullName} _v{i};");
						}
					}
				}
			}
			#endregion

			#region Definition

			sb.AppendLine($"[DebuggerDisplay(\"{{DebuggerDisplay,nq}}\")]");
			sb.AppendLine(CompilerGeneratedAttribute);
			sb.AppendIntend();
			sb.Append($"{model.TypeKind.Replace("struct", "partial struct").Replace("class", "partial class")} {model.FullName}");
			if (!model.IsRef)
			{
				sb.Append($" : IEquatable<{model.FullName}>");
			}
			sb.AppendLine();
			using (sb.EnterScope(false))
			{
				sb.AppendLine($"private readonly {enumName} _kind;");

				if (layout == OneOfLayoutKind.Boxing)
				{
					sb.AppendLine("private readonly object? _value;");
				}
				else if (layout == OneOfLayoutKind.Composition)
				{
					for (int i = 0; i < count; i++)
					{
						if (model.TypeArgs[i].FullName != VoidType)
						{
							sb.AppendLine($"private readonly {model.TypeArgs[i].FullName} _v{i};");
						}
					}
				}
				else
				{
					if (hasRef)
					{
						sb.AppendLine("private readonly object? _ref;");
					}
					if (hasVal)
					{
						sb.AppendLine("#pragma warning disable CS0649");
						sb.AppendLine($"private readonly {unionName} _data;");
						sb.AppendLine("#pragma warning restore CS0649");
					}
				}
				sb.AppendLine();

			#endregion

				#region Constructors

				sb.AppendLine("#pragma warning disable CS8618");
				if (isClass) { sb.AppendLine("#pragma warning disable CS8618"); }

				string masterParams = layout switch
				{
					OneOfLayoutKind.Composition => string.Join(", ", model.TypeArgs.Select((t, i) => $"{t.FullName} v{i}")),
					OneOfLayoutKind.Boxing => "object? value",
					_ => (hasRef && hasVal) ? "object? @ref, " + unionName + " data" : hasRef ? "object? @ref" : unionName + " data"
				};

				sb.AppendLine(Inline);
				sb.AppendLine($"private {model.Name}({enumName} kind, {masterParams})");

				using (sb.EnterScope())
				{
					sb.AppendLine("this._kind = kind;");
					if (layout == OneOfLayoutKind.Composition)
					{
						for (int i = 0; i < count; i++)
						{
							if (model.TypeArgs[i].FullName != VoidType)
							{
								sb.AppendLine($"this._v{i} = v{i};");
							}
						}
					}
					else if (layout == OneOfLayoutKind.Boxing)
					{
						sb.AppendLine("this._value = value;");
					}
					else if (layout == OneOfLayoutKind.ExplicitUnion)
					{
						if (hasRef)
						{
							sb.AppendLine("this._ref = @ref;");
						}
						if (hasVal)
						{
							sb.AppendLine("this._data = data;");
						}
					}
				}

				if (!model.AllowEmpty)
				{
					sb.AppendLine(Inline);
					sb.AppendLine($"public {model.Name}()");
					using (sb.EnterScope())
					{
						sb.AppendLine($"{ThrowHelper}.ThrowEmpty(nameof({model.FullName}));");
					}
				}

				var typeGroups = model.TypeArgs
					.Select((type, index) => (type, index))
					.GroupBy(x => x.type.FullName);

				foreach (var group in typeGroups)
				{
					var type = group.First().type;
					var indices = group.Select(x => x.index).ToList();

					if (indices.Count == 1)
					{
						int i = indices[0];
						sb.AppendLine(Inline);
						sb.AppendLine($"public {model.Name}({type.FullName} value)");

						using (sb.EnterScope())
						{
							GenerateAssignment(type, i, sb);
							sb.AppendLine($"this._kind = {enumName}.{model.FieldNames[i]};");
						}
					}
					else
					{
						var validKinds = string.Join(" || ", indices.Select(idx => $"kind == {enumName}.{model.FieldNames[idx]}"));

						sb.AppendLine(Inline);
						sb.AppendLine($"public {model.Name}({type.FullName} value, {enumName} kind)");
						using (sb.EnterScope())
						{
							sb.AppendLine($"if (!({validKinds}))");
							using (sb.EnterScope())
							{
								sb.AppendLine($"{ThrowHelper}.ThrowInvalid<{enumName}>(0, 0);");
							}
							if (type.FullName != VoidType)
							{
								GenerateAssignment(type, -1, sb, indices);
							}
							sb.AppendLine("this._kind = kind;");
						}
					}
				}

				if (isClass) sb.AppendLine("#pragma warning restore CS8618");
				sb.AppendLine("#pragma warning restore CS8618");

				void GenerateAssignment(GenerationModel.TypeInfoModel t, int index, IndentedWriter sb, List<int>? ambiguousIndices = null)
				{
					if (t.FullName == VoidType) { return; }

					if (t.IsReferenceType)
					{
						sb.AppendLine($"if (value is null) {{ {ThrowHelper}.ThrowNull(nameof(value)); }}");
					}

					if (layout == OneOfLayoutKind.ExplicitUnion && !t.IsReferenceType)
					{
						sb.AppendLine("global::System.Runtime.CompilerServices.Unsafe.SkipInit(out this._data);");
					}

					if (ambiguousIndices == null)
					{
						sb.AppendLine($"this.{UnsafeSet(index)} = value;");
					}
					else
					{
						sb.AppendLine("switch (kind)");
						using (sb.EnterScope())
						{
							foreach (var idx in ambiguousIndices)
							{
								sb.AppendLine($"case {enumName}.{model.FieldNames[idx]}: this.{UnsafeSet(idx)} = value; break;");
							}
						}
					}
				}

				#endregion

				if (model.AllowEmpty)
				{
					sb.AppendLine($"public static {model.FullName} Empty => new();");
					sb.AppendLine();
				}

				#region GetForce

				for (int i = 0; i < count; i++)
				{
					var type = model.TypeArgs[i];
					var field = model.FieldNames[i];
					sb.AppendLine($"private{read} {type.FullName} {field}Force => {UnsafeGet(i)};");
				}
				sb.AppendLine();

				#endregion

				#region Get / Is

				sb.AppendLine($"public{read} {enumName} Kind => _kind;");

				sb.AppendLine($"public{read} int Index => (int)_kind;");
				sb.AppendLine($"public{read} object? BoxValue => _kind switch");
				sb.AppendLine("{");
				sb.Increase();

				for (int i = 0; i < count; i++)
				{
					sb.AppendLine($"{enumName}.{model.FieldNames[i]} => (object?){model.FieldNames[i]}Force,");
				}
				sb.AppendLine("_ => null,");

				sb.Decrease();
				sb.AppendLine("};");
				sb.AppendLine();

				for (int i = 0; i < count; i++)
				{
					var type = model.TypeArgs[i];
					var field = model.FieldNames[i];
					sb.AppendLine($"public{read} {type.FullName} {field}");
					using (sb.EnterScope())
					{
						sb.AppendLine("get");
						using (sb.EnterScope(false))
						{
							sb.AppendLine($"if (_kind != {enumName}.{field})");
							using (sb.EnterScope(false))
							{
								sb.AppendLine($"{ThrowHelper}.ThrowInvalid<{enumName}>((int){enumName}.{field}, (int)_kind);");
							}
							sb.AppendLine($"return {UnsafeGet(i)};");
						}
					}

					sb.AppendLine($"public{read} {type.FullName}? {field}OrDefault => _kind == {enumName}.{field} ? {UnsafeGet(i)}: default;");
					sb.AppendLine();
				}

				if (model.AllowEmpty)
				{
					sb.AppendLine($"public{read} bool IsEmpty => _kind == {enumName}.Empty;");
				}
				foreach (var field in model.FieldNames)
				{
					sb.AppendLine($"public{read} bool Is{field} => _kind == {enumName}.{field};");
				}
				sb.AppendLine();

				#endregion

				#region TryGet / Is

				for (int i = 0; i < count; i++)
				{
					var type = model.TypeArgs[i];
					var field = model.FieldNames[i];
					sb.AppendLine(Inline);
					sb.AppendLine($"public{read} bool TryGet{field}([NotNullWhen(true)] out {type.FullName}{(type.IsReferenceType ? "?" : string.Empty)} OutValue)");
					using (sb.EnterScope())
					{
						sb.AppendLine($"if (_kind == {enumName}.{field})");
						using (sb.EnterScope())
						{
							sb.AppendLine($"OutValue = {UnsafeGet(i)};");
							sb.AppendLine("return true;");
						}
						sb.AppendLine("OutValue = default!;");
						sb.AppendLine("return false;");
					}
					sb.AppendLine();
				}

				sb.AppendLine(Inline);
				sb.AppendLine($"public{read} bool TryGet<TGet>([NotNullWhen(true)] out TGet? value)");
				using (sb.EnterScope())
				{
					var grouped = model.TypeArgs.GroupBy(t => t.FullName);
					foreach (var group in grouped)
					{
						sb.AppendLine($"if (typeof(TGet) == typeof({group.Key}))");
						using (sb.EnterScope())
						{
							foreach (var t in group)
							{
								int index = model.TypeArgs.IndexOf(t);
								sb.AppendLine($"if (_kind == {enumName}.{model.FieldNames[index]})");
								using (sb.EnterScope(false))
								{
									sb.AppendLine($"{model.TypeArgs[index].FullName} temp = {UnsafeGet(index)};");
									sb.AppendLine($"value = Unsafe.As<{group.Key}, TGet>(ref temp)!;");
									sb.AppendLine("return true;");
								}
							}
						}
					}

					sb.AppendLine("value = default;");
					sb.AppendLine("return false;");
				}

				#endregion

				#region TryPick

				for (int i = 0; i < count; i++)
				{
					var type = model.TypeArgs[i];
					var field = model.FieldNames[i];
					sb.AppendLine(Inline);
					sb.AppendLine($"public{read} bool TryPick{field}([NotNullWhen(true)] out {type.FullName}{(type.IsReferenceType ? "?" : string.Empty)} OutValue, [NotNullWhen(false)] out {model.FullName}{(model.TypeKind.Contains("class") ? "?" : string.Empty)} Remainder)");
					using (sb.EnterScope())
					{
						sb.AppendLine($"if (_kind == {enumName}.{field})");
						using (sb.EnterScope())
						{
							sb.AppendLine($"OutValue = {UnsafeGet(i)};");
							sb.AppendLine($"Remainder = default!;");
							sb.AppendLine("return true;");
						}
						sb.AppendLine("Remainder = this;");
						sb.AppendLine("OutValue = default!;");
						sb.AppendLine("return false;");
					}
				}

				#endregion

				#region Switch / Match

				sb.AppendLine(Inline);
				sb.AppendIntend();
				sb.Append($"public{read} void Switch(");
				for (int i = 0; i < count; i++)
				{
					var type = model.TypeArgs[i];
					var field = model.FieldNames[i];
					sb.Append($"Action<{type.FullName}> On{field}");
					if (i < count - 1)
					{
						sb.Append(", ");
					}
				}
				if (model.AllowEmpty)
				{
					sb.Append(", Action OnEmpty");
				}
				sb.AppendLine(")");
				using (sb.EnterScope())
				{
					sb.AppendLine("switch(_kind)");
					using (sb.EnterScope(false))
					{
						for (int i = 0; i < count; i++)
						{
							var field = model.FieldNames[i];
							sb.AppendLine($"case {enumName}.{model.FieldNames[i]}: {{ On{field}.Invoke({UnsafeGet(i)}); break; }}");
						}
						if (model.AllowEmpty)
						{
							sb.AppendLine("default: { OnEmpty.Invoke(); break; }");
						}
						else
						{
							sb.AppendLine($"default: {{ throw new ArgumentNullException(\"{model.Name} is empty\"); }}");
						}
					}
				}

				sb.AppendLine(Inline);
				sb.AppendIntend();
				sb.Append($"public{read} TResult Match<TResult>(");
				for (int i = 0; i < count; i++)
				{
					var type = model.TypeArgs[i];
					var field = model.FieldNames[i];
					sb.Append($"Func<{type.FullName}, TResult> On{field}");
					if (i < count - 1)
					{
						sb.Append(", ");
					}
				}
				if (model.AllowEmpty)
				{
					sb.Append(", Func<TResult> OnEmpty");
				}
				sb.AppendLine(")");
				using (sb.EnterScope())
				{
					sb.AppendLine("switch(_kind)");
					using (sb.EnterScope(false))
					{
						for (int i = 0; i < count; i++)
						{
							var field = model.FieldNames[i];
							sb.AppendLine($"case {enumName}.{model.FieldNames[i]}: {{ return On{field}.Invoke({UnsafeGet(i)}); }}");
						}
						if (model.AllowEmpty)
						{
							sb.AppendLine("default: { return OnEmpty.Invoke(); }");
						}
						else
						{
							sb.AppendLine($"default: {{ throw new ArgumentNullException(\"{model.Name} is empty\"); }}");
						}
					}
				}

				#endregion

				#region Async SwitchAsync / MatchAsync

				if (!model.IsRef)
				{
					sb.AppendLine(Inline);
					sb.AppendIntend();
					sb.Append($"public{read} async ValueTask SwitchAsync(");
					for (int i = 0; i < count; i++)
					{
						var type = model.TypeArgs[i];
						var field = model.FieldNames[i];
						sb.Append($"Func<{type.FullName}, ValueTask> On{field}");
						if (i < count - 1 || model.AllowEmpty)
						{
							sb.Append(", ");
						}
					}
					if (model.AllowEmpty)
					{
						sb.Append("Func<ValueTask> OnEmpty");
					}
					sb.AppendLine(")");
					using (sb.EnterScope())
					{
						sb.AppendLine("switch(_kind)");
						sb.AppendLine("{");
						sb.Increase();
						for (int i = 0; i < count; i++)
						{
							sb.AppendLine($"case {enumName}.{model.FieldNames[i]}: {{ await On{model.FieldNames[i]}.Invoke({UnsafeGet(i)}); break; }}");
						}
						if (model.AllowEmpty)
						{
							sb.AppendLine("default: { await OnEmpty.Invoke(); break; }");
						}
						else
						{
							sb.AppendLine($"default: {{ throw new InvalidOperationException(\"{model.Name} is empty\"); }}");
						}
						sb.Decrease();
						sb.AppendLine("};");
					}

					sb.AppendLine(Inline);
					sb.AppendIntend();
					sb.Append($"public{read} async ValueTask<TResult> MatchAsync<TResult>(");
					for (int i = 0; i < count; i++)
					{
						var type = model.TypeArgs[i];
						var field = model.FieldNames[i];
						sb.Append($"Func<{type.FullName}, ValueTask<TResult>> On{field}");
						if (i < count - 1 || model.AllowEmpty)
						{
							sb.Append(", ");
						}
					}
					if (model.AllowEmpty)
					{
						sb.Append("Func<ValueTask<TResult>> OnEmpty");
					}
					sb.AppendLine(")");
					using (sb.EnterScope())
					{
						sb.AppendLine("return _kind switch");
						sb.AppendLine("{");
						sb.Increase();
						for (int i = 0; i < count; i++)
						{
							sb.AppendLine($"{enumName}.{model.FieldNames[i]} => await On{model.FieldNames[i]}.Invoke({UnsafeGet(i)}),");
						}
						if (model.AllowEmpty)
						{
							sb.AppendLine("_ => await OnEmpty.Invoke()");
						}
						else
						{
							sb.AppendLine($"_ => throw new InvalidOperationException(\"{model.Name} is empty\")");
						}
						sb.Decrease();
						sb.AppendLine("};");
					}
				}
				#endregion

				#region Map

				for (int i = 0; i < count; i++)
				{
					var type = model.TypeArgs[i];
					var field = model.FieldNames[i];

					sb.AppendLine(Inline);
					sb.AppendLine($"public{read} {model.FullName} Map{field}(Func<{type.FullName}, {type.FullName}> mapper)");
					using (sb.EnterScope())
					{
						sb.AppendLine($"if (_kind == {enumName}.{field})");
						using (sb.EnterScope())
						{
							if (sameTypes.Contains(i))
							{
								sb.AppendLine($"return new {model.FullName}(mapper.Invoke({UnsafeGet(i)}), {enumName}.{field});");
							}
							else
							{
								sb.AppendLine($"return new {model.FullName}(mapper.Invoke({UnsafeGet(i)}));");
							}
						}
						sb.AppendLine("return this;");
					}
				}

				#endregion

				#region Equality

				if (!model.IsRef)
				{
					if (!model.UserFuncs.Any(f =>
						f.Item1 == "Equals" &&
						f.Item2.Length == 1 &&
						f.Item2[0] == model.FullName))
					{
						sb.AppendLine($"public{read} bool Equals({model.FullName}{(isClass ? "?" : string.Empty)} other)");
						using (sb.EnterScope())
						{
							if (isClass)
							{
								sb.AppendLine("if (other == null) { return false; }");
							}
							sb.AppendLine("if (_kind != other._kind) { return false; }");
							sb.AppendLine("return _kind switch");
							sb.AppendLine("{");
							sb.Increase();
							for (int i = 0; i < count; i++)
							{
								sb.AppendLine($"{enumName}.{model.FieldNames[i]} => EqualityComparer<{model.TypeArgs[i].FullName}>.Default.Equals({UnsafeGet(i)}, other.{model.FieldNames[i]}Force),");
							}
							sb.AppendLine("_ => true");
							sb.Decrease();
							sb.AppendLine("};");
						}
					}

					if (!model.UserFuncs.Any(f =>
						f.Item1 == "Equals" &&
						f.Item2.Length == 1 &&
						(f.Item2[0] == "object?" || f.Item2[0] == "object")))
					{
						sb.AppendLine($"public{read} override bool Equals(object? obj) => obj is " + model.FullName + " other && Equals(other);");
						sb.AppendLine();
					}

					if (!model.UserFuncs.Any(f =>
						f.Item1 == "GetHashCode()" &&
						f.Item2.Length == 0))
					{
						sb.AppendLine($"public{read} override int GetHashCode()");
						using (sb.EnterScope())
						{
							sb.AppendLine("var hash = new HashCode();");
							sb.AppendLine("hash.Add(_kind);");
							sb.AppendLine("switch(_kind)");
							using (sb.EnterScope())
							{
								for (int i = 0; i < count; i++)
								{
									sb.AppendLine($"case {enumName}.{model.FieldNames[i]}: {{ hash.Add({UnsafeGet(i)}); break; }}");
								}
							}
							sb.AppendLine("return hash.ToHashCode();");
						}
					}

					if (!isClass)
					{
						sb.AppendLine($"public static bool operator ==({model.FullName} left, {model.FullName} right) => left.Equals(right);");
						sb.AppendLine($"public static bool operator !=({model.FullName} left, {model.FullName} right) => !left.Equals(right);");
					}
					else
					{
						sb.AppendLine($"public static bool operator ==({model.FullName}? left, {model.FullName}? right) => ReferenceEquals(left, right) ? true : (((object?)left) == null ? false : left.Equals(right));");
						sb.AppendLine($"public static bool operator !=({model.FullName}? left, {model.FullName}? right) => ReferenceEquals(left, right) ? false :(((object?)left) == null ? true : !left.Equals(right));");
					}
					sb.AppendLine();
				}

				#endregion

				#region Deconstruct

				sb.Append($"\t\tpublic{read} void Deconstruct(out {enumName} kind");
				for (int i = 0; i < count; i++)
				{
					sb.Append($", out {model.TypeArgs[i].FullName}? {model.FieldNames[i].ToLower()}");
				}
				sb.AppendLine(")");
				using (sb.EnterScope())
				{
					sb.AppendLine("kind = _kind;");
					for (int i = 0; i < count; i++)
					{
						sb.AppendLine($"{model.FieldNames[i].ToLower()} = Is{model.FieldNames[i]} ? {UnsafeGet(i)} : default;");
					}
				}

				#endregion

				#region Operators

				foreach (int i in uniqTypes)
				{
					var type = model.TypeArgs[i];
					var field = model.FieldNames[i];
					if (model.TypeArgs.Count(x => x.FullName == type.FullName) >= 2) { continue; }
					sb.AppendLine(Inline);
					sb.AppendIntend();
					sb.Append($"public static implicit operator {model.FullName}({type.FullName} value) => ");
					if (type.IsReferenceType)
					{
						sb.Append("(value == null) ? throw new ArgumentNullException(nameof(value)) : new(value);");
						sb.AppendLine();
					}
					else
					{
						sb.Append("new(value);");
						sb.AppendLine();
					}
					sb.AppendLine(Inline);
					sb.AppendLine($"public static explicit operator {type.FullName}({model.FullName} source) => source.{field};");
					sb.AppendLine();
				}

				#endregion

				#region IEnumerable

				if (!model.IsRef)
				{
					sb.AppendLine(Inline);
					sb.AppendLine($"public{read} IEnumerable<{model.FullName}> AsEnumerable()");
					using (sb.EnterScope())
					{
						if (model.AllowEmpty)
						{
							sb.AppendLine("if (IsEmpty) { yield break; }");
						}
						sb.AppendLine("yield return this;");
					}
				}

				#endregion

				#region Tuple Conversion 

				if (!model.IsRef && model.TypeArgs.Length <= 7)
				{
					var tupleTypes = string.Join(", ", model.TypeArgs.Select(t => $"{t.FullName}?"));
					var tupleFull = $"(int Kind, {tupleTypes})";

					sb.AppendLine($"public{read} {tupleFull} AsTuple => _kind switch");
					sb.AppendLine("{");
					sb.Increase();

					for (int i = 0; i < count; i++)
					{
						var values = Enumerable.Repeat("default", count).ToArray();
						values[i] = UnsafeGet(i);
						sb.AppendLine($"{enumName}.{model.FieldNames[i]} => ({i + 1}, {string.Join(", ", values)}),");
					}
					sb.AppendLine("_ => (0, " + string.Join(", ", Enumerable.Repeat("default", count)) + ")");

					sb.Decrease();
					sb.AppendLine("};");
					sb.AppendLine();

					sb.AppendLine(Inline);
					sb.AppendLine($"public static {model.FullName} FromTuple({tupleFull} tuple) => tuple.Kind switch");
					sb.AppendLine("{");
					sb.Increase();
					for (int i = 0; i < count; i++)
					{
						if (sameTypes.Contains(i))
						{
							sb.AppendLine($"{i + 1} => new(({model.TypeArgs[i].FullName})tuple.Item{i + 2}!, {enumName}.{model.FieldNames[i]}),");
						}
						else
						{
							sb.AppendLine($"{i + 1} => new(({model.TypeArgs[i].FullName})tuple.Item{i + 2}!),");
						}
					}
					sb.AppendLine($"_ => {(model.AllowEmpty ? "Empty" : $"{ThrowHelper}.ThrowEmpty<{model.FullName}>()")}");
					sb.Decrease();
					sb.AppendLine("};");
					sb.AppendLine();

					sb.AppendLine(Inline);
					sb.AppendLine($"public static implicit operator {model.FullName}({tupleFull} tuple) => FromTuple(tuple);");
					sb.AppendLine();
				}

				#endregion

				#region ToString / DebuggerDisplay

				if (!model.UserFuncs.Any(f =>
						f.Item1 == "ToString" &&
						f.Item2.Length == 0))
				{
					sb.AppendLine(Inline);
					sb.AppendLine($"public{read} override string? ToString() => _kind switch");
					sb.AppendLine("{");
					sb.Increase();
					for (int i = 0; i < count; i++)
					{
						sb.AppendLine($"{enumName}.{model.FieldNames[i]} => ({UnsafeGet(i)}).ToString(),");
					}
					sb.AppendLine("_ => \"Empty\"");
					sb.Decrease();
					sb.AppendLine("};");
					sb.AppendLine();
				}

				sb.AppendLine("#if DEBUG");
				sb.AppendLine($"private{read} string DebuggerDisplay => _kind switch");
				sb.AppendLine("{");
				sb.Increase();
				for (int i = 0; i < count; i++)
				{
					sb.AppendLine($"{enumName}.{model.FieldNames[i]} => $\"{model.TypeArgs[i].ShortName}({{{model.FieldNames[i]}}}) - {{Unsafe.SizeOf<{model.FullName}>()}} bytes\",");
				}
				sb.AppendLine("_ => \"Empty\"");
				sb.Decrease();
				sb.AppendLine("};");
				sb.AppendLine("#endif");

				#endregion

				sb.AppendLine($"public enum {enumName} : int");
				using (sb.EnterScope(false))
				{
					sb.AppendLine("Empty = 0,");
					for (int i = 0; i < count; i++)
					{
						sb.AppendLine($"{model.FieldNames[i]} = {i + 1},");
					}
				}
			}

			if (hasNamespace)
			{
				sb.Decrease();
				sb.AppendLine("}");
			}

			return sb.ToString();

			string UnsafeGet(int i)
			{
				var type = model.TypeArgs[i];

				if (model.TypeArgs[i].FullName == VoidType) { return $"default({VoidType})"; }

				if (layout == OneOfLayoutKind.Boxing)
				{
					return $"({type.FullName})_value!";
				}
				else if (layout == OneOfLayoutKind.Composition)
				{
					return $"_v{i}!";
				}
				else if (layout == OneOfLayoutKind.ExplicitUnion)
				{
					if (type.IsReferenceType)
					{
						return $"({type.FullName})_ref!";
					}
					else
					{
						return $"_data._v{i}";
					}
				}
				return string.Empty;
			}

			string UnsafeSet(int i)
			{
				var type = model.TypeArgs[i];

				if (model.TypeArgs[i].FullName == VoidType) { return $""; }

				if (layout == OneOfLayoutKind.Boxing)
				{
					return "_value";
				}
				else if (layout == OneOfLayoutKind.Composition)
				{
					return $"_v{i}";
				}
				else if (type.IsReferenceType)
				{
					return "_ref";
				}
				else
				{
					return $"_data._v{i}";
				}
			}
		}

		public static string GenerateSystemJsonSource(GenerationModel model)
		{
			var jsonClass = $"{model.Name}JsonConverter";
			string enumName = $"OneOf{model.Name}";
			var fullName = model.FullName;
			var jsonClassName = model.Name.Split('<')[0] + "JsonConverter";
			string read = model.TypeKind.Contains("class") ? string.Empty : " readonly";

			bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
			bool isGeneric = model.FullName.Contains("<");

			IndentedWriter sb = new();

			sb.AppendLine($"// <auto-generated by {nameof(OneOfGenerator)} />");
			sb.AppendLine("#nullable enable");
			sb.AppendLine("using System;");
			sb.AppendLine("using System.Text.Json;");
			sb.AppendLine("using System.Text.Json.Serialization;");
			sb.AppendLine("#if NET7_0_OR_GREATER");
			sb.AppendLine("using System.Text;");
			sb.AppendLine("#endif");
			sb.AppendLine();

			if (hasNamespace)
			{
				sb.AppendLine($"namespace {model.Namespace}");
				sb.AppendLine("{");
				sb.Increase();
			}

			if (!isGeneric)
			{
				sb.AppendLine($"[JsonConverter(typeof({jsonClass}))]");
			}

			sb.AppendLine($"partial {model.TypeKind} {fullName}");
			using (sb.EnterScope())
			{
				sb.AppendLine($"internal class {jsonClass} : JsonConverter<{fullName}>");
				using (sb.EnterScope(newLine: false))
				{
					sb.AppendLine($"private static{read} JsonEncodedText KindProp = JsonEncodedText.Encode(\"Kind\");");
					sb.AppendLine($"private static{read} JsonEncodedText ValueProp = JsonEncodedText.Encode(\"Value\");");
					sb.AppendLine();

					sb.AppendLine($"public override {fullName} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)");
					using (sb.EnterScope())
					{
						sb.AppendLine("if (reader.TokenType != JsonTokenType.StartObject)");
						using (sb.EnterScope(newLine: false))
						{
							sb.AppendLine("throw new JsonException(\"Expected StartObject token.\");");
						}
						sb.AppendLine();
						sb.AppendLine("int kindInt = 0;");
						sb.AppendLine("JsonElement valueElement = default;");
						sb.AppendLine("bool valueFound = false;");
						sb.AppendLine();
						sb.AppendLine("while (reader.Read())");
						using (sb.EnterScope())
						{
							sb.AppendLine("if (reader.TokenType == JsonTokenType.EndObject)");
							using (sb.EnterScope(newLine: false))
							{
								sb.AppendLine("break;");
							}
							sb.AppendLine();
							sb.AppendLine("if (reader.TokenType != JsonTokenType.PropertyName)");
							using (sb.EnterScope(newLine: false))
							{
								sb.AppendLine("continue;");
							}
							sb.AppendLine();

							sb.AppendLine("#if NET7_0_OR_GREATER");
							sb.AppendLine("if (reader.ValueTextEquals(\"Kind\"u8))");
							sb.AppendLine("#else");
							sb.AppendLine("if (reader.ValueTextEquals(KindProp.EncodedUtf8Bytes))");
							sb.AppendLine("#endif");
							using (sb.EnterScope(newLine: false))
							{
								sb.AppendLine("reader.Read();");
								sb.AppendLine("kindInt = reader.GetInt32();");
							}

							sb.AppendLine("#if NET7_0_OR_GREATER");
							sb.AppendLine("else if (reader.ValueTextEquals(\"Value\"u8))");
							sb.AppendLine("#else");
							sb.AppendLine("else if (reader.ValueTextEquals(ValueProp.EncodedUtf8Bytes))");
							sb.AppendLine("#endif");
							using (sb.EnterScope(newLine: false))
							{
								sb.AppendLine("reader.Read();");
								sb.AppendLine("valueElement = JsonElement.ParseValue(ref reader);");
								sb.AppendLine("valueFound = true;");
							}
							sb.AppendLine("else");
							using (sb.EnterScope(newLine: false))
							{
								sb.AppendLine("reader.Skip();");
							}
						}

						sb.AppendLine();
						sb.AppendLine($"var kind = ({enumName})kindInt;");
						sb.AppendLine("return kind switch");
						sb.AppendLine("{");
						sb.Increase();
						for (int i = 0; i < model.TypeArgs.Length; i++)
						{
							var type = model.TypeArgs[i].FullName;
							var field = model.FieldNames[i];
							var extraArg = model.TypeArgs.Count(x => x.FullName == type) >= 2 ? $", {enumName}.{field}" : string.Empty;
							sb.AppendLine($"{enumName}.{field} => valueFound ? new(valueElement.Deserialize<{type}?>(options) ?? default!{extraArg}) : default!,");
						}
						sb.AppendLine(model.AllowEmpty ? "_ => default" : "_ => throw new JsonException(\"Unknown Kind\")");
						sb.Decrease();
						sb.AppendLine("};");
					}

					sb.AppendLine($"public override void Write(Utf8JsonWriter writer, {fullName} value, JsonSerializerOptions options)");
					using (sb.EnterScope(newLine: false))
					{
						sb.AppendLine("writer.WriteStartObject();");
						sb.AppendLine("writer.WriteNumber(KindProp, (int)value._kind);");

						if (model.AllowEmpty)
						{
							sb.AppendLine("if (value.IsEmpty)");
							using (sb.EnterScope(newLine: false))
							{
								sb.AppendLine("writer.WriteEndObject();");
								sb.AppendLine("return;");
							}
							sb.AppendLine();
						}

						sb.AppendLine("writer.WritePropertyName(ValueProp);");
						sb.AppendLine("value.Switch(");
						sb.Increase();
						for (int i = 0; i < model.TypeArgs.Length; i++)
						{
							sb.AppendIntend();
							sb.Append($"on{model.FieldNames[i]} => JsonSerializer.Serialize(writer, on{model.FieldNames[i]}, options)");
							sb.Append(i < model.TypeArgs.Length - 1 || model.AllowEmpty ? "," : "");
							sb.AppendLine();
						}
						if (model.AllowEmpty)
						{
							sb.AppendLine("() => { }");
						}
						sb.Decrease();
						sb.AppendLine(");");
						sb.AppendLine("writer.WriteEndObject();");
					}
				}
			}

			if (hasNamespace)
			{
				sb.Decrease();
				sb.AppendLine("}");
			}

			return sb.ToString();
		}

		public static string GenerateNewtonsoftJsonSource(GenerationModel model)
		{
			var jsonClass = $"{model.Name}NewtonsoftConverter";
			string enumName = $"OneOf{model.Name}";
			var fullName = model.FullName;
			bool isClass = model.TypeKind.Contains("class");
			string nullableSign = isClass ? "?" : string.Empty;
			bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
			bool isGeneric = model.FullName.Contains("<");

			var sb = new IndentedWriter();
			sb.AppendLine("// <auto-generated by OneOfGenerator for Newtonsoft.Json support />");
			sb.AppendLine("#nullable enable");
			sb.AppendLine("using System;");
			sb.AppendLine("using Newtonsoft.Json;");
			sb.AppendLine("using Newtonsoft.Json.Linq;");
			sb.AppendLine();

			if (hasNamespace)
			{
				sb.AppendLine($"namespace {model.Namespace}");
				sb.AppendLine("{");
				sb.Increase();
			}

			if (!isGeneric)
			{
				sb.AppendLine($"[JsonConverter(typeof({jsonClass}))]");
			}

			sb.AppendLine($"partial {model.TypeKind} {fullName}");
			using (sb.EnterScope())
			{
				sb.AppendLine($"internal class {jsonClass} : JsonConverter<{fullName}>");
				using (sb.EnterScope(newLine: false))
				{
					sb.AppendLine("private const string KindProp = \"Kind\";");
					sb.AppendLine("private const string ValueProp = \"Value\";");
					sb.AppendLine();

					sb.AppendLine($"public override {fullName}{nullableSign} ReadJson(JsonReader reader, Type objectType, {fullName}{nullableSign} existingValue, bool hasExistingValue, JsonSerializer serializer)");
					using (sb.EnterScope())
					{
						sb.AppendLine("if (reader.TokenType == JsonToken.Null)");
						using (sb.EnterScope(newLine: false)) sb.AppendLine("return default;");

						sb.AppendLine();
						sb.AppendLine("if (reader.TokenType != JsonToken.StartObject)");
						using (sb.EnterScope(newLine: false)) sb.AppendLine("throw new JsonException(\"Expected StartObject token.\");");

						sb.AppendLine();
						sb.AppendLine("JObject jo = JObject.Load(reader);");
						sb.AppendLine();
						sb.AppendLine("if (!jo.TryGetValue(KindProp, StringComparison.OrdinalIgnoreCase, out JToken? kindToken))");
						using (sb.EnterScope(newLine: false)) sb.AppendLine("throw new JsonException(\"Missing 'Kind' property.\");");

						sb.AppendLine();
						sb.AppendLine("int kindInt = kindToken.Value<int>();");
						sb.AppendLine($"var kind = ({enumName})kindInt;");
						sb.AppendLine();
						sb.AppendLine("jo.TryGetValue(ValueProp, StringComparison.OrdinalIgnoreCase, out JToken? valueToken);");
						sb.AppendLine();
						sb.AppendLine("return kind switch");
						sb.AppendLine("{");
						sb.Increase();
						for (int i = 0; i < model.TypeArgs.Length; i++)
						{
							var type = model.TypeArgs[i].FullName;
							var field = model.FieldNames[i];
							var ctorArgs = model.TypeArgs.Count(x => x.FullName == type) >= 2
								? $", {enumName}.{field}"
								: string.Empty;

							sb.AppendLine($"{enumName}.{field} => valueToken != null ? new(valueToken.ToObject<{type}?>(serializer) ?? default!{ctorArgs}) : default!,");
						}

						if (model.AllowEmpty)
						{
							sb.AppendLine("_ => default");
						}
						else
						{
							sb.AppendLine("_ => throw new JsonException($\"Unknown Kind: {kindInt}\")");
						}

						sb.Decrease();
						sb.AppendLine("};");
					}

					sb.AppendLine($"public override void WriteJson(JsonWriter writer, {fullName}{nullableSign} value, JsonSerializer serializer)");
					using (sb.EnterScope(newLine: false))
					{
						sb.AppendLine("writer.WriteStartObject();");
						sb.AppendLine();

						if (isClass)
						{
							sb.AppendLine("if (value == null) { writer.WriteEndObject(); return; }");
							sb.AppendLine();
						}

						sb.AppendLine("writer.WritePropertyName(KindProp);");
						sb.AppendLine("writer.WriteValue((int)value._kind);");
						sb.AppendLine();

						if (model.AllowEmpty)
						{
							sb.AppendLine("if (value.IsEmpty)");
							using (sb.EnterScope(newLine: false))
							{
								sb.AppendLine("writer.WriteEndObject();");
								sb.AppendLine("return;");
							}
							sb.AppendLine();
						}

						sb.AppendLine("writer.WritePropertyName(ValueProp);");
						sb.AppendLine("value.Switch(");
						sb.Increase();
						for (int i = 0; i < model.TypeArgs.Length; i++)
						{
							var field = model.FieldNames[i];
							var comma = (i < model.TypeArgs.Length - 1 || model.AllowEmpty) ? "," : string.Empty;
							sb.AppendLine($"on{field} => serializer.Serialize(writer, on{field}){comma}");
						}

						if (model.AllowEmpty)
						{
							sb.AppendLine("() => { }");
						}
						sb.Decrease();
						sb.AppendLine(");");
						sb.AppendLine();
						sb.AppendLine("writer.WriteEndObject();");
					}
				}
			}

			if (hasNamespace)
			{
				sb.Decrease();
				sb.AppendLine("}");
			}

			return sb.ToString();
		}

		public static string GenerateMemoryPackSource(GenerationModel model)
		{
			var formatterClass = $"{model.Name}Formatter";
			string enumName = $"OneOf{model.Name}";
			var fullName = model.FullName;
			bool isClass = model.TypeKind.Contains("class");
			bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);

			var sb = new IndentedWriter();
			sb.AppendLine($"// <auto-generated by {nameof(OneOfGenerator)} for MemoryPack support />");
			sb.AppendLine("#nullable enable");
			sb.AppendLine("using System;");
			sb.AppendLine("using MemoryPack;");
			sb.AppendLine();

			if (hasNamespace)
			{
				sb.AppendLine($"namespace {model.Namespace}");
				sb.AppendLine("{");
				sb.Increase();
			}

			sb.AppendLine($"partial {model.TypeKind} {fullName}");
			using (sb.EnterScope())
			{
				sb.AppendLine($"static {model.Name}()");
				using (sb.EnterScope(newLine: false))
				{
					sb.AppendLine($"MemoryPackFormatterProvider.Register(new {formatterClass}());");
				}
				sb.AppendLine();

				sb.AppendLine($"internal class {formatterClass} : MemoryPackFormatter<{fullName}>");
				using (sb.EnterScope(newLine: false))
				{
					sb.AppendLine($"public override void Serialize<TBufferWriter>(ref MemoryPackWriter<TBufferWriter> writer, scoped ref {fullName}{(isClass ? "?" : string.Empty)} value)");
					using (sb.EnterScope())
					{
						if (isClass)
						{
							sb.AppendLine("if (value == null) { writer.WriteNullObjectHeader(); return; }");
						}
						sb.AppendLine("writer.WriteUnmanaged((byte)value._kind);");
						sb.AppendLine();
						sb.AppendLine("switch (value._kind)");
						using (sb.EnterScope(newLine: false))
						{
							for (int i = 0; i < model.TypeArgs.Length; i++)
							{
								var type = model.TypeArgs[i].FullName;
								var field = model.FieldNames[i];
								sb.AppendLine($"case {enumName}.{field}:");
								sb.Increase();
								sb.AppendLine($"writer.WriteValue<{type}>(value.{field}Force);");
								sb.AppendLine("break;");
								sb.Decrease();
							}
						}
					}

					sb.AppendLine($"public override void Deserialize(ref MemoryPackReader reader, scoped ref {fullName}{(isClass ? "?" : string.Empty)} value)");
					using (sb.EnterScope(newLine: false))
					{
						sb.AppendLine("if (reader.PeekIsNull())");
						using (sb.EnterScope(newLine: false))
						{
							sb.AppendLine("reader.Advance(1);");
							sb.AppendLine("value = default;");
							sb.AppendLine("return;");
						}
						sb.AppendLine();

						sb.AppendLine("reader.ReadUnmanaged(out byte k);");
						sb.AppendLine($"var kind = ({enumName})k;");
						sb.AppendLine();

						sb.AppendLine("value = kind switch");
						sb.AppendLine("{");
						sb.Increase();
						for (int i = 0; i < model.TypeArgs.Length; i++)
						{
							var type = model.TypeArgs[i].FullName;
							var field = model.FieldNames[i];
							sb.AppendLine($"{enumName}.{field} => new {fullName}(reader.ReadValue<{type}>()!{(model.TypeArgs.Count(x => x.FullName == type) >= 2 ? $", {enumName}.{field}" : string.Empty)}),");
						}

						sb.AppendLine("_ => default");
						sb.Decrease();
						sb.AppendLine("};");
					}
				}
			}

			if (hasNamespace)
			{
				sb.Decrease();
				sb.AppendLine("}");
			}

			return sb.ToString();
		}

		public static string GenerateThrowHelper(string? nameSpace)
		{
			bool hasNamespace = !string.IsNullOrWhiteSpace(nameSpace);

			string indent = hasNamespace ? "\t" : "";

			StringBuilder sb = new(1024);
			sb.AppendLine($"// <auto-generated by {nameof(OneOfGenerator)} for Throw />");
			sb.AppendLine("using System;");
			sb.AppendLine("using System.Runtime.CompilerServices;");
			sb.AppendLine();

			if (hasNamespace)
			{
				sb.AppendLine($"namespace {nameSpace}");
				sb.AppendLine("{");
			}

			sb.Append(
				$$"""
				{{indent}}internal static class OneOfThrowHelper
				{{indent}}{
				{{indent}}	[global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
				{{indent}}	[MethodImpl(MethodImplOptions.NoInlining)]
				{{indent}}	internal static void ThrowInvalid<T>(int expected, int current) where T : struct, Enum
				{{indent}}	{
				{{indent}}		throw new InvalidOperationException($"Cannot access {(T)(object)expected}. Current kind is {(T)(object)current}");
				{{indent}}	}

				{{indent}}	[global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
				{{indent}}	[MethodImpl(MethodImplOptions.NoInlining)]
				{{indent}}	internal static void ThrowEmpty(string typeName)
				{{indent}}	{
				{{indent}}		throw new InvalidOperationException($"{typeName} is empty or not initialized");
				{{indent}}	}

				{{indent}}	[global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
				{{indent}}	[MethodImpl(MethodImplOptions.NoInlining)]
				{{indent}}	internal static T ThrowEmpty<T>()
				{{indent}}	{
				{{indent}}		throw new InvalidOperationException($"{nameof(T)} is empty or not initialized");
				{{indent}}	}

				{{indent}}	[global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
				{{indent}}	[MethodImpl(MethodImplOptions.NoInlining)]
				{{indent}}	internal static void ThrowNull(string typeName)
				{{indent}}	{
				{{indent}}		throw new NullReferenceException($"{typeName} cannot be initialized with null");
				{{indent}}	}

				{{indent}}	[global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
				{{indent}}	[MethodImpl(MethodImplOptions.NoInlining)]
				{{indent}}	internal static void ThrowInvalidType(string typeName)
				{{indent}}	{
				{{indent}}		throw new NullReferenceException($"{typeName} cannot be initialized with null");
				{{indent}}	}
				{{indent}}}
				"""
			);

			if (hasNamespace)
			{
				sb.AppendLine();
				sb.Append("}");
			}

			return sb.ToString();
		}

		private static (OneOfLayoutKind Strategy, string Reason) DetermineLayout(GenerationModel model)
		{
			bool isClass = model.TypeKind.Contains("class");
			bool hasRefStructInside = model.TypeArgs.Any(t => t.IsRefStruct);

			if (model.RequestedLayout == OneOfLayoutKind.Boxing)
			{
				if (hasRefStructInside)
				{
					return (OneOfLayoutKind.Composition, "Boxing is impossible with ref structs");
				}
				return (OneOfLayoutKind.Boxing, string.Empty);
			}

			if (model.RequestedLayout == OneOfLayoutKind.ExplicitUnion)
			{
				if (isClass)
				{
					return (OneOfLayoutKind.Composition, "ExplicitUnion is not supported for classes");
				}
				if (model.IsGeneric)
				{
					return (OneOfLayoutKind.Composition, "ExplicitUnion is unstable with generic value types");
				}
				if (hasRefStructInside)
				{
					return (OneOfLayoutKind.Composition, "ExplicitUnion is not supported with ref structs");
				}
				return (OneOfLayoutKind.ExplicitUnion, string.Empty);
			}

			return (OneOfLayoutKind.Composition, "Default fallback");
		}
	}
}
